name: Add issues to project

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: read
  projects: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/cchaksa/projects/1
          github-token: ${{ secrets.TOKEN_GITHUB }}